(in-package #:self-improving-agent-harness/tests)

(defun run-logging-tests ()
  (let* ((directory #P"/tmp/self-improving-agent-harness-logging-test/")
         (path (merge-pathnames "chat.log" directory)))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging directory)
           (self-improving-agent-harness::log-interaction
            :info "turn-received" :content "read README.md")
           (self-improving-agent-harness::log-interaction
            :error "turn-failed" :message "Tool handler \"run_shell\" failed.")
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "\"level\":\"info\"" content)
                          "interaction log records info events")
             (ensure-true (search "read README.md" content)
                          "interaction log retains user-turn content")
             (ensure-true (search "Tool handler \\\"run_shell\\\" failed." content)
                          "interaction log retains the safe failure message")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (let* ((directory #P"/tmp/self-improving-agent-harness-turn-logging-test/")
         (path (merge-pathnames "chat.log" directory))
         (backend (make-instance 'scripted-backend :name "scripted" :responses '()))
         (session (make-chat-session :backend backend :model "test/model" :handlers '())))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging directory)
           (handler-case
               (chat-session-turn session "trigger a scripted backend failure")
             (error () nil))
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "turn-received" content)
                          "chat session logs the received user turn")
             (ensure-true (search "turn-failed" content)
                          "chat session logs failed turns")
             (ensure-true (search "Test backend exhausted" content)
                          "chat session logs the failure message")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (let* ((directory #P"/tmp/self-improving-agent-harness-tool-logging-test/")
         (path (merge-pathnames "chat.log" directory))
         (arguments (make-hash-table :test #'equal)))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (setf (gethash "command" arguments) "exit 9")
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging directory)
           (handler-case
               (run-shell-tool arguments)
             (error () nil))
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "tool-call" content)
                          "shell tool logs its command invocation")
             (ensure-true (search "tool-failed" content)
                          "shell tool logs failed command execution")
             (ensure-true (search "exit 9" content)
                          "shell tool log identifies the failing command")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (format t "Interaction logging tests passed.~%")
  t)
