(in-package #:self-improving-agent-harness/tests)

(defun run-logging-tests ()
  (let* ((directory #P"/tmp/self-improving-agent-harness-logging-test/")
         (path (merge-pathnames "chat.log" directory)))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging directory)
           (self-improving-agent-harness::log-interaction
            :info "turn-received" :content "OPENROUTER_API_KEY=sk-test-do-not-persist")
           (self-improving-agent-harness::log-interaction
            :error "turn-failed" :message "Tool handler \"run_shell\" failed.")
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "\"level\":\"info\"" content)
                          "interaction log records info events")
             (ensure-true (search "turn-received" content)
                          "interaction log retains the turn lifecycle event")
             (ensure-true (not (search "sk-test-do-not-persist" content))
                          "interaction log excludes secret-bearing turn content")
             (ensure-true (not (search "Tool handler \\\"run_shell\\\" failed." content))
                          "interaction log excludes arbitrary failure details")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (let* ((directory #P"/tmp/self-improving-agent-harness-turn-logging-test/")
         (path (merge-pathnames "chat.log" directory))
         (backend (make-instance 'scripted-backend :name "scripted" :responses '()))
         (session (make-chat-session :backend backend :model "test/model" :handlers '())))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging directory)
           (handler-case
               (chat-session-turn session "trigger a scripted backend failure")
             (error () nil))
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "turn-received" content)
                          "chat session logs the received user turn")
             (ensure-true (search "turn-failed" content)
                          "chat session logs failed turns")
             (ensure-true (not (search "Test backend exhausted" content))
                          "chat session excludes the backend failure detail")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (let* ((directory #P"/tmp/self-improving-agent-harness-tool-logging-test/")
         (path (merge-pathnames "chat.log" directory))
         (arguments (make-hash-table :test #'equal)))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (setf (gethash "command" arguments) "exit 9")
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging directory)
           (handler-case
               (run-shell-tool arguments)
             (error () nil))
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "tool-call" content)
                          "shell tool logs its command invocation")
             (ensure-true (search "tool-failed" content)
                          "shell tool logs failed command execution")
             (ensure-true (not (search "exit 9" content))
                          "shell tool log excludes the failing command")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (let* ((directory #P"/tmp/self-improving-agent-harness-correlation-logging-test/")
         (path (merge-pathnames "chat.log" directory)))
    (when (probe-file directory)
      (uiop:delete-directory-tree directory :validate t))
    (unwind-protect
         (progn
           (self-improving-agent-harness::configure-interaction-logging directory)
           (let ((self-improving-agent-harness::*interaction-session-id* "session-test-16")
                 (self-improving-agent-harness::*interaction-turn-number* 2))
             (self-improving-agent-harness::log-interaction :info "turn-completed")
             (let ((*error-output* (make-string-output-stream)))
               (dolist (event '("turn-submitted" "turn-completed" "turn-failed" "turn-empty"))
                 (self-improving-agent-harness:emit-chat-event event))
               (let ((events (get-output-stream-string *error-output*)))
                 (ensure-true (search "\"session_id\":\"session-test-16\"" events)
                              "chat boundary events include their session ID")
                 (ensure-true (search "\"turn\":2" events)
                              "chat boundary events include their submitted turn number")
                 (dolist (event '("turn-submitted" "turn-completed" "turn-failed" "turn-empty"))
                   (ensure-true (search event events)
                                "chat boundary event states remain distinguishable")))))
           (let ((content (uiop:read-file-string path)))
             (ensure-true (search "\"session_id\":\"session-test-16\"" content)
                          "shared diagnostic log includes the session ID")
             (ensure-true (search "\"turn\":2" content)
                          "shared diagnostic log includes the turn number")))
      (self-improving-agent-harness::configure-interaction-logging nil)
      (when (probe-file directory)
        (uiop:delete-directory-tree directory :validate t))))
  (format t "Interaction logging tests passed.~%")
  t)
