(defpackage #:self-improving-agent-harness
  (:use #:cl)
  (:export
   #:backend
   #:backend-name
   #:complete
   #:run-tool-loop
   #:configure-interaction-logging
   #:log-interaction
   #:emit-chat-event
   #:*interaction-turn-initiator*
   #:*interaction-log-record-content*
   #:*interaction-log-content-limit*
   #:run-shell-tool
   #:*tool-result-content-limit*
   #:truncate-tool-result-content
   #:*run-shell-after-hooks*
   #:*run-shell-default-timeout-seconds*
   #:*run-shell-timeout-kill-after-seconds*
   #:report-run-shell-timing
   #:run-run-shell-after-hooks
   #:reload-harness-tool
   #:chat-session
   #:make-chat-session
   #:chat-session-history
   #:chat-session-options
   #:chat-session-handlers
   #:chat-session-max-rounds
   ;; Session accounting remains a compatibility surface for the supervisor
   ;; evidence path while the reloadable CLI owns interaction orchestration.
   #:chat-session-last-provider-responses
   #:chat-session-last-accounting
   #:chat-session-turn
   #:chat-session-failed-turn-p
   #:note-chat-session-failure
   #:completion-request
   #:make-completion-request
   #:completion-request-model
   #:completion-request-messages
   #:completion-request-options
   #:completion-response
   #:make-completion-response
   #:completion-response-text
   #:completion-response-model
   #:completion-response-raw
   #:completion-response-tool-calls
   #:completion-response-finish-reason
   #:completion-response-provider-request-id
   #:completion-response-usage
   #:openrouter-backend
   #:make-openrouter-backend
   #:openrouter-backend-base-url
   #:openrouter-backend-api-key
   #:run-harness
   ;; chat CLI (reloadable via reload_harness)
   #:+chat-input-prompt+
   #:+chat-prompt-separator+
   #:*pending-chat-prompt-close*
   #:maybe-write-chat-prompt-closing
   #:read-chat-input-line
   #:write-chat-prompt-closing
   #:write-chat-prompt
   #:process-interactive-user-turn
   #:process-interactive-input
   #:report-completed-chat-turn
   #:write-final-response-outcome
   #:run-interactive
   #:run-interactive-loop
   #:run-one-shot
   #:run-chat-cli
   #:handle-interactive-command
   #:chat-options
   #:chat-handlers
   #:shell-tool
   #:reload-tool
   #:resolve-chat-session-options
   #:resolve-chat-session-handlers
   #:ensure-chat-session-system-prompt
   #:+chat-system-prompt+
   #:*pending-synthetic-followups*
   #:*suppress-synthetic-followup-scheduling*
   #:schedule-synthetic-followup
   #:take-next-synthetic-followup
   #:clear-synthetic-followups
   #:maybe-run-synthetic-followup-turns
   #:run-synthetic-followup-turn))
